package:
  name: pflib
  version: {{ environ.get('GIT_DESCRIBE_TAG') | replace("-",".") }}
source:
  path: ../..
build:
  exclude:
    - build**
    - .git**
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - cmake
    - make
    - python
    - boost
    - rogue
    - nlohmann_json
    - yaml-cpp
  run:
    - python
    - boost
    - rogue
    - nlohmann_json
    - yaml-cpp
