inherit:
  calib_offset: 15
  sipm_bias: 
    value : 3784
    rocs: [0,1,2,3]
  hgcrocs:
    inherit: 
      Top:
        Phase: 9
cob1-dpm0:
  calib_offset: 16
  # sipm_bias is as given above
  hgcrocs:
    inherit:
      Top: 
        Phase: 8
    0 :
      Top :
        Phase : 7
    2 :
      Top :
        Phase : 6
    3 :
      # will have top.phase = 8
cob1-dpm1:
  # calib_offset is 15
  sipm_bias:
    value: 3800
    rocs: [0,1,3]
  hgcrocs:
    0 :
      Top :
        Phase : 8
    1 :
      # will have top.phase = 9
    3 :
      # will have top.phase = 9
