ChEprxGrp:
  00:
    channel_locked: 1
  
  01:
    channel_locked: 1
  
  02:
    channel_locked: 1
  
  03:
    channel_locked: 1
  
  04:
    channel_locked: 1
  
  05:
    channel_locked: 1

  06:
    channel_locked: 1

  07:
    channel_locked: 1

  08:
    channel_locked: 1

  09:
    channel_locked: 1

  10:
    channel_locked: 1

  11:
    channel_locked: 1