ChAligner:
  00:
    pattern_match: 1
    snapshot_dv: 1
  01:
    pattern_match: 1
    snapshot_dv: 1
  02:
    pattern_match: 1
    snapshot_dv: 1
  03:
    pattern_match: 1
    snapshot_dv: 1
  04:
    pattern_match: 1
    snapshot_dv: 1
  05:
    pattern_match: 1
    snapshot_dv: 1
  06:
    pattern_match: 1
    snapshot_dv: 1
  07:
    pattern_match: 1
    snapshot_dv: 1
  08:
    pattern_match: 1
    snapshot_dv: 1
  09:
    pattern_match: 1
    snapshot_dv: 1
  10:
    pattern_match: 1
    snapshot_dv: 1
  11:
    pattern_match: 1
    snapshot_dv: 1
