ChAligner:
  00:
    pattern_match: 1
    snapshot_dv: 1
    select: 1
  01:
    pattern_match: 1
    snapshot_dv: 1
    select: 1
  02:
    pattern_match: 1
    snapshot_dv: 1
    select: 1
  03:
    pattern_match: 1
    snapshot_dv: 1
    select: 1
  04:
    pattern_match: 1
    snapshot_dv: 1
    select: 1
  05:
    pattern_match: 1
    snapshot_dv: 1
    select: 1