ETx:
  00:
    invert_data: 1
FormatterBuffer:
  Global:
    align_serializer:
      00: 27
    active_etxs: 1
    idle_pattern: 5592405 # "0x555555"
    #idle_pattern: 16777200 # "0xFFFFF0"
    #idle_pattern: 0
    link_reset_pattern: 290 #"0x122"
    #link_reset_pattern: 426 #"0x1aa"
