ETx:
  00:
    invert_data: 0
  01:
    invert_data: 1
  02:
    invert_data: 0
  03:
    invert_data: 0
  04:
    invert_data: 0
  05:
    invert_data: 0
FormatterBuffer:
  Global:
    align_serializer:
      00: 31
      01: 13
      02: 0
      03: 0
      04: 0
      05: 0
    active_etxs: 1
      #idle_pattern: 5592405 # "0x555555"
    #idle_pattern: 16777200 # "0xFFFFF0"
    #idle_pattern: 0
    link_reset_pattern: 290 #"0x122"
    #link_reset_pattern: 426 #"0x1aa"
