Aligner:
  Global:
    orbsyn_cnt_load_val: 1
    orbsyn_cnt_snapshot: 3080
    match_pattern_val: 
      00: 2505397589 #0x95555555
      01: 2773833045 #0xa5555555
    match_mask_val: 
      00: 0
      01: 0
    i2c_snapshot_en: 0
    snapshot_en: 1
    orbsyn_cnt_max_val: 3563
    freeze_output_enable: 0
    freeze_output_enable_all_channels_locked: 0
ChAligner: 
  00:
   per_ch_align_en : 1
  01:
   per_ch_align_en : 1
  02:
   per_ch_align_en : 1
  03:
   per_ch_align_en : 1
  04:
   per_ch_align_en : 1
  05:
   per_ch_align_en : 1
  06:
   per_ch_align_en : 1
  07:
   per_ch_align_en : 1
  08:
   per_ch_align_en : 1
  09:
   per_ch_align_en : 1
  10:
   per_ch_align_en : 1
  11:
   per_ch_align_en : 1
ERx:
  00:
   enable: 1
   invert_data: 1
  01:
   enable: 1
   invert_data: 0
  02:
   enable: 1
   invert_data: 0
  03:
   enable: 1
   invert_data: 0
  04:
   enable: 1
   invert_data: 0
  05:
   enable: 1
   invert_data: 0
  06:
   enable: 1
   invert_data: 0
  07:
   enable: 1
   invert_data: 0
  08:
   enable: 1
   invert_data: 0
  09:
   enable: 1
   invert_data: 0
  10:
   enable: 1
   invert_data: 0
  11:
   enable: 1
   invert_data: 0
