ChEprxGrp:
  00:
    train_channel: 0
  01:
    train_channel: 0
  02:
    train_channel: 0
  03:
    train_channel: 0
  04:
    train_channel: 0
  05:
    train_channel: 0
  06:
    train_channel: 0
  07:
    train_channel: 0
  08:
    train_channel: 0
  09:
    train_channel: 0
  10:
    train_channel: 0
  11:
    train_channel: 0


