build_aarch64_almalinux9:
  extends: .build_template_aarch64
  image:
    name: gitlab-registry.cern.ch/hgcal-daq-sw/serenity-daq/docker_images/base/almalinux9-aarch64
  variables:
    OS: almalinux
    VERSION: "9"
    TGT_ARCH: aarch64
