#Note the marked board specific settings

#Basic analog settings
Global_Analog_*:
  Gain_conv: 4 #4 for data taking, but zero when adjusting pre-amplifier
  Delay40: 2 ##Will probably stay in range 1-3, tuning this is not very useful for beam data
  Delay65: 2 #Will probably stay in range 1-3
  Delay87: 2 #Will probably stay in range 1-3
  Delay9: 2 #Will probably stay in range 1-3

Reference_Voltage_0:
  Tot_vref: 447 #Board specific
  Toa_vref: 110 #Board specific
  Inv_vref: 420
  Calib_dac: 0
  IntCtest: 0
  ExtCtest: 0
Reference_Voltage_1:
  Tot_vref: 442 #Board specific
  Toa_vref: 100 #Board specific
  Inv_vref: 425
  Calib_dac: 0
  IntCtest: 0
  ExtCtest: 0

#Recommendations
Master_TDC_*:
  GLOBAL_TA_SELECT_GAIN_TOA: 3
  GLOBAL_TA_SELECT_GAIN_TOT: 3
  GLOBAL_MODE_NO_TOT_SUB: 0
  GLOBAL_LATENCY_TIME: 10
  GLOBAL_MODE_FTDC_TOA_S0: 0
  GLOBAL_MODE_FTDC_TOA_S1: 1
  GLOBAL_SEU_TIME_OUT: 1
  BIAS_FOLLOWER_CAL_P_D: 0
  BIAS_FOLLOWER_CAL_P_EN: 0
  INV_FRONT_40MHZ: 0
  START_COUNTER: 1
  CALIB_CHANNEL_DLL: 0
  VD_CTDC_P_D: 0
  VD_CTDC_P_DAC_EN: 0
  EN_MASTER_CTDC_VOUT_INIT: 0
  EN_MASTER_CTDC_DLL: 1
  BIAS_CAL_DAC_CTDC_P_D: 0
  CTDC_CALIB_FREQUENCY: 2
  GLOBAL_MODE_TOA_DIRECT_OUTPUT: 0
  BIAS_I_CTDC_D: 24
  FOLLOWER_CTDC_EN: 1
  GLOBAL_EN_BUFFER_CTDC: 0
  VD_CTDC_N_FORCE_MAX: 1
  VD_CTDC_N_D: 0
  VD_CTDC_N_DAC_EN: 0
  CTRL_IN_REF_CTDC_P_D: 0
  CTRL_IN_REF_CTDC_P_EN: 0
  CTRL_IN_SIG_CTDC_P_D: 0
  CTRL_IN_SIG_CTDC_P_EN: 0
  GLOBAL_INIT_DAC_B_CTDC: 0
  BIAS_CAL_DAC_CTDC_P_EN: 1
  VD_FTDC_P_D: 0
  VD_FTDC_P_DAC_EN: 0
  EN_MASTER_FTDC_VOUT_INIT: 0
  EN_MASTER_FTDC_DLL: 1
  BIAS_CAL_DAC_FTDC_P_D: 0
  FTDC_CALIB_FREQUENCY: 2
  EN_REF_BG: 1
  BIAS_I_FTDC_D: 24
  FOLLOWER_FTDC_EN: 1
  GLOBAL_EN_BUFFER_FTDC: 0
  VD_FTDC_N_FORCE_MAX: 1
  VD_FTDC_N_D: 0
  VD_FTDC_N_DAC_EN: 0
  CTRL_IN_SIG_FTDC_P_D: 0
  CTRL_IN_SIG_FTDC_P_EN: 0
  GLOBAL_INIT_DAC_B_FTDC: 0
  BIAS_CAL_DAC_FTDC_P_EN: 0
  CTRL_IN_REF_FTDC_P_D: 0
  CTRL_IN_REF_FTDC_P_EN: 0
  GLOBAL_DISABLE_TOT_LIMIT: 0
  GLOBAL_FORCE_EN_CLK: 0
  GLOBAL_FORCE_EN_OUTPUT_DATA: 0
  GLOBAL_FORCE_EN_TOT: 0

#Timing parameters for link stability
Top:
  BIAS_I_PLL_D: 63
  DIV_PLL: 0
  EN_HIGH_CAPA: 1
  EN_LOCK_CONTROL: 0
  EN_PHASESHIFT: 1
  EN_PLL: 1
  EN_PLL_EXT: 0
  EN_REF_BG: 1
  ERROR_LIMIT_SC: 0
  ET_AMPLITUDE: 3
  ET_PRE_PHASE: 0
  ET_PRE_SCALE: 0
  FOLLOWER_PLL_EN: 1
  ORBITSYNC_SC: 0
  PHASE: 13 #Not important for beam data since the particles do not come synchronized with the clock
  PLLLOCKEDSC: 1
  PLL_PROBE_AMPLITUDE: 3
  PLL_PROBE_PRE_PHASE: 0
  PLL_PROBE_PRE_SCALE: 0
  SEL_40M_EXT: 0
  SEL_L1_FCMD: 1
  SEL_ORBITSYNC_FCMD: 1
  SEL_PLL_LOCKED: 1
  SEL_RESYNC_FCMD: 1
  SEL_STROBE_FCMD: 1
  VOUT_INIT_EN: 0
  VOUT_INIT_EXT_D: 0
  VOUT_INIT_EXT_EN: 0

Digital_Half_*:
  L1Offset: 85 #Change this?

#Reset channel-wise pedestal adjustment
Channel_*:
  Dacb: 55
  Sign_dac: 0
  Ref_dac_inv: 0

#Channel-wise pedestal adjustments should go after this, for board specific files
Channel_0:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_1:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 7
Channel_2:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_3:
  Dacb: 56
  Sign_dac: 0
  Ref_dac_inv: 14
Channel_4:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_5:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_6:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_7:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_8:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_9:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 6
Channel_10:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 12
Channel_11:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_12:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_13:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 18
Channel_14:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_15:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_16:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 15
Channel_17:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_18:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_19:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_20:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_21:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 13
Channel_22:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_23:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 7
Channel_24:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_25:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_26:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 6
Channel_27:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 6
Channel_28:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 14
Channel_29:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 14
Channel_30:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 15
Channel_31:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 15
Channel_32:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_33:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_34:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_35:
  Dacb: 63
  Sign_dac: 0
  Ref_dac_inv: 30



Channel_36:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_37:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 7
Channel_38:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_39:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 12
Channel_40:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 4
Channel_41:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_42:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 10
Channel_43:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 2
Channel_44:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 7
Channel_45:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_46:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 6
Channel_47:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 0
Channel_48:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 5
Channel_49:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 7
Channel_50:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 0
Channel_51:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 2
Channel_52:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 5
Channel_53:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 6
Channel_54:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_55:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_56:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 3
Channel_57:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 1
Channel_58:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 4
Channel_59:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 3
Channel_60:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_61:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_62:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 5
Channel_63:
  Dacb: 59
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_64:
  Dacb: 61
  Sign_dac: 0
  Ref_dac_inv: 9
Channel_65:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 4
Channel_66:
  Dacb: 60
  Sign_dac: 0
  Ref_dac_inv: 8
Channel_67:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 2
Channel_68:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 11
Channel_69:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 5
Channel_70:
  Dacb: 57
  Sign_dac: 0
  Ref_dac_inv: 3
Channel_71:
  Dacb: 58
  Sign_dac: 0
  Ref_dac_inv: 2
