FROM ubuntu:22.04
LABEL maintainer="Tom Eichlersmith <eichl008@umn.edu>"
RUN apt-get update &&\
    apt-get --yes install \
      gcc \
      g++ \
      cmake \
      clang \
      clang-format \
      clang-tools \
      libreadline-dev \
      libboost-all-dev \
      wget \
      nlohmann-json3-dev \
      python3 \
      python3-numpy \
      python3-dev \
      python3-yaml \
      libyaml-cpp-dev \
      git
