FROM almalinux:9.4
LABEL maintainer="Tom Eichlersmith <eichl008@umn.edu>"
LABEL os.version="almalinux:9.4"
RUN yum -y install \
  gcc \
  g++ \
  clang \
  clang-tools-extra \
  cmake \
  readline-devel \
  boost-devel \
  json-devel \
  wget \
  python3 \
  python-yaml \
  git
RUN mkdir src &&\
    wget -q -O- https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz |\
      tar -xz --strip-components=1 --directory src &&\
    cmake \
      -S src/ \
      -B src/build \
      -DYAML_BUILD_SHARED_LIBS=ON \
    &&\
    cmake --build src/build --target install &&\
    rm -rf src
