
name: docs

on:
  push:
    branches:
      - 'main'

jobs:
  update-docs:
    runs-on: ubuntu-20.04
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive' # for doxygen-awesome-css
      - 
        name: install doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.2.linux.bin.tar.gz
          ln -s doxygen-1.9.2/bin/doxygen doxygen
      - 
        name: set version
        run: |
          _version_tag=$(git describe --tags)
          echo ${_version_tag}
          echo "PROJECT_NUMBER = ${_version_tag}" >> docs/doxyfile
      - 
        name: run doxygen
        run: ./doxygen docs/doxyfile
      - 
        name: publish generated content
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.LDMX_ORG_TOKEN }}
