
name: docs

on:
  push:
    tags:
      - 'v**'
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: 'recursive' # for doxygen-awesome-css
      - 
        name: set version
        run: |
          _version_tag=$(git describe --tags)
          echo ${_version_tag}
          echo "PROJECT_NUMBER = ${_version_tag}" >> docs/doxyfile
      -
        name: Run Doxygen to build C++ Docs
        uses: mattnotmitt/doxygen-action@v1.12
        with:
          doxyfile-path: docs/doxyfile #relative to working directory
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/html

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-docs
    steps:
      -
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
